/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import javax.swing.JOptionPane;
import model.GranCarnaryRent;
import model.Reserva;
import model.TarjetaCredito;
import model.Usuario;

/**
 *
 * @author Juanma
 */
public class PagarReserva extends javax.swing.JFrame {
    private GranCarnaryRent granCarnaryRent;
    private Usuario user;
    private Reserva reserva;
    /**
     * Creates new form PagarReserva
     */
    public PagarReserva() {
        initComponents();
    }
    
    public PagarReserva(GranCarnaryRent granCarnaryRent, Usuario usuario, Reserva reserva) {
        this.granCarnaryRent = granCarnaryRent;
        this.user = usuario;
        this.reserva = reserva;
        this.setLocationRelativeTo(null);
        initComponents();
        printTarjetas();
    }
    
    public void printTarjetas(){
        String [] text = this.user.getTarjetasArr();
        ListaDeTarjetas.setListData(text);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaDeTarjetas = new javax.swing.JList<>();
        Pagar = new javax.swing.JButton();
        AñadirTarjeta = new javax.swing.JButton();
        Volver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setFont(new java.awt.Font("Malgun Gothic", 1, 24)); // NOI18N
        jLabel5.setText("Tarjetas Disponibles");

        ListaDeTarjetas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(ListaDeTarjetas);

        Pagar.setText("Pagar");
        Pagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PagarActionPerformed(evt);
            }
        });

        AñadirTarjeta.setText("Añadir Tarjeta");
        AñadirTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AñadirTarjetaActionPerformed(evt);
            }
        });

        Volver.setText("Volver");
        Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(68, 68, 68))
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Pagar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Volver)
                        .addGap(18, 18, 18)
                        .addComponent(AñadirTarjeta)
                        .addGap(40, 40, 40))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(41, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Pagar)
                            .addComponent(AñadirTarjeta))
                        .addContainerGap(33, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Volver)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverActionPerformed
        // TODO add your handling code here:
        VerReservas abrir = new VerReservas(this.granCarnaryRent, this.user);
        abrir.setVisible(true);
        String [] text = new String[0];
        ListaDeTarjetas.setListData(text);
        this.setVisible(false);
    }//GEN-LAST:event_VolverActionPerformed

    private void AñadirTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AñadirTarjetaActionPerformed
        // TODO add your handling code here:
        AñadirTarjetaReserva pantalla = new AñadirTarjetaReserva(this.granCarnaryRent, this.user, this.reserva);
        pantalla.setVisible(true);
        String [] text = new String[0];
        ListaDeTarjetas.setListData(text);
        this.setVisible(false);
    }//GEN-LAST:event_AñadirTarjetaActionPerformed

    private void PagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PagarActionPerformed
        // TODO add your handling code here:
         try{
            for (TarjetaCredito tarjeta : this.user.getTarjetas()){
                System.out.println(tarjeta.toString());
                System.out.println(ListaDeTarjetas.getSelectedValue());
                if(ListaDeTarjetas.getSelectedValue().equals(tarjeta.toString())){
                    JOptionPane.showMessageDialog(null,
                    "Su pago ha sido realizado de manera exitosa",
                    "Pago realizado",
                    JOptionPane.INFORMATION_MESSAGE);
                    reserva.setPagado(true);
                    VerReservas abrir = new VerReservas(this.granCarnaryRent, this.user);
                    abrir.setVisible(true);
                    String [] text = new String[0];
                    ListaDeTarjetas.setListData(text);
                    this.setVisible(false);
                    break;
                }
            }
        }catch(java.lang.NullPointerException e){
            JOptionPane.showMessageDialog(null,
                "No ha seleccionado correctamente el elemento",
                "Seleccione una tarjeta",
                JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_PagarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PagarReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PagarReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PagarReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PagarReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PagarReserva().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AñadirTarjeta;
    private javax.swing.JList<String> ListaDeTarjetas;
    private javax.swing.JButton Pagar;
    private javax.swing.JButton Volver;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
