/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import javax.swing.JOptionPane;
import model.GranCarnaryRent;
import model.TarjetaCredito;
import model.Usuario;

/**
 *
 * @author Juanma
 */
public class PantallaVerTarjetas extends javax.swing.JFrame {
    private GranCarnaryRent granCarnaryRent;
    private Usuario user;
    /**
     * Creates new form PantallaVerTarjetas
     */
    public PantallaVerTarjetas() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public PantallaVerTarjetas(GranCarnaryRent granCarnaryRent, Usuario usuario) {
        initComponents();
        this.userLabel1.setText(usuario.getNombre());
        this.userSaldoLabel.setText(Float.toString(usuario.getSaldo()));
        this.granCarnaryRent = granCarnaryRent;
        this.user = usuario;
        this.setLocationRelativeTo(null);
        printTarjetas();
    }
    
    public void printTarjetas(){
        String [] text = this.user.getTarjetasArr();
        ListaDeTarjetas.setListData(text);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        userLabel1 = new javax.swing.JLabel();
        userSaldoLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaDeTarjetas = new javax.swing.JList<>();
        AñadirTarjeta = new javax.swing.JButton();
        EliminarTarjeta = new javax.swing.JButton();
        VolverButton = new javax.swing.JButton();

        userLabel.setText("User");

        jLabel1.setFont(new java.awt.Font("Lucida Handwriting", 1, 24)); // NOI18N
        jLabel1.setText("GranCarnaryRent");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        userLabel1.setText("User");

        userSaldoLabel.setText("User saldo");

        jLabel2.setFont(new java.awt.Font("Lucida Handwriting", 1, 24)); // NOI18N
        jLabel2.setText("Tarjetas de Crédito");

        ListaDeTarjetas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(ListaDeTarjetas);

        AñadirTarjeta.setText("Añadir Tarjeta");
        AñadirTarjeta.setActionCommand("AñadirTarjeta");
        AñadirTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AñadirTarjetaActionPerformed(evt);
            }
        });

        EliminarTarjeta.setText("Eliminar Tarjeta");
        EliminarTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarTarjetaActionPerformed(evt);
            }
        });

        VolverButton.setText("Volver");
        VolverButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(userLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(userSaldoLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(AñadirTarjeta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(EliminarTarjeta))
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))
                        .addGap(0, 55, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(VolverButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userLabel1)
                    .addComponent(userSaldoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AñadirTarjeta)
                    .addComponent(EliminarTarjeta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(VolverButton)
                .addGap(5, 5, 5))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VolverButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverButtonActionPerformed
        // TODO add your handling code here:
        MenuPrincipal menu = new MenuPrincipal(this.granCarnaryRent, this.user);
        menu.setVisible(true);
        String [] text = new String[0];
        ListaDeTarjetas.setListData(text);
        this.setVisible(false);
    }//GEN-LAST:event_VolverButtonActionPerformed

    private void EliminarTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarTarjetaActionPerformed
        // TODO add your handling code here:
        try{
            for (TarjetaCredito tarjeta : this.user.getTarjetas()){
                if(ListaDeTarjetas.getSelectedValue().equals(tarjeta.toString())){
                    this.user.deleteCreditCard(tarjeta);
                    JOptionPane.showMessageDialog(null,
                    "La tarjeta ha sido eliminada correctamente",
                    "Tarjeta eliminada exitósamente",
                    JOptionPane.INFORMATION_MESSAGE);
                    this.printTarjetas();
                    break;
                }
            }
        }catch(java.lang.NullPointerException e){
            JOptionPane.showMessageDialog(null,
                "No ha seleccionado correctamente el elemento",
                "Seleccione una tarjeta",
                JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_EliminarTarjetaActionPerformed

    private void AñadirTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AñadirTarjetaActionPerformed
        // TODO add your handling code here:
        AñadirTarjeta pantalla = new AñadirTarjeta(this.granCarnaryRent, this.user);
        pantalla.setVisible(true);
        String [] text = new String[0];
        ListaDeTarjetas.setListData(text);
        this.setVisible(false);
    }//GEN-LAST:event_AñadirTarjetaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaVerTarjetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaVerTarjetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaVerTarjetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaVerTarjetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaVerTarjetas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AñadirTarjeta;
    private javax.swing.JButton EliminarTarjeta;
    private javax.swing.JList<String> ListaDeTarjetas;
    private javax.swing.JButton VolverButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel userLabel;
    private javax.swing.JLabel userLabel1;
    private javax.swing.JLabel userSaldoLabel;
    // End of variables declaration//GEN-END:variables
}
