/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import model.GranCarnaryRent;


/**
 *
 * @author Juanma
 */
public class PantallaCrearCuenta extends javax.swing.JFrame {
    
    private GranCarnaryRent granCarnaryRent;
    /**
     * Creates new form PantallaCrearCuenta
     */
    public PantallaCrearCuenta() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public PantallaCrearCuenta(GranCarnaryRent granCarnaryRent) {
        initComponents();
        this.granCarnaryRent=granCarnaryRent;
        this.setLocationRelativeTo(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lNombreC = new javax.swing.JLabel();
        lContraseñaC = new javax.swing.JLabel();
        lEmailC = new javax.swing.JLabel();
        NombreCuenta = new javax.swing.JTextField();
        ContraseñaCuenta = new javax.swing.JTextField();
        EmailCuenta = new javax.swing.JTextField();
        Telefono = new javax.swing.JLabel();
        TelefonoCuenta = new javax.swing.JTextField();
        bAceptarC = new javax.swing.JButton();
        bVolverC = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Rellene los siguientes datos:");

        lNombreC.setText("Nombre:");
        lNombreC.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        lContraseñaC.setText("Contraseña:");

        lEmailC.setText("Email:");

        EmailCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailCuentaActionPerformed(evt);
            }
        });

        Telefono.setText("Teléfono:");

        TelefonoCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelefonoCuentaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lContraseñaC)
                            .addComponent(lEmailC)
                            .addComponent(lNombreC)
                            .addComponent(Telefono))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(NombreCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(ContraseñaCuenta)
                            .addComponent(EmailCuenta)
                            .addComponent(TelefonoCuenta))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NombreCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lNombreC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lContraseñaC, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ContraseñaCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lEmailC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EmailCuenta))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Telefono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TelefonoCuenta))
                .addGap(4, 4, 4))
        );

        bAceptarC.setText("Aceptar");
        bAceptarC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bAceptarCMouseClicked(evt);
            }
        });

        bVolverC.setText("Volver");
        bVolverC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVolverCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(bAceptarC)
                .addGap(42, 42, 42)
                .addComponent(bVolverC)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bAceptarC)
                    .addComponent(bVolverC))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bVolverCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVolverCActionPerformed
        // TODO add your handling code here:
        PantallaInicio abrir = new PantallaInicio(granCarnaryRent);
        abrir.setVisible(true);
        
        this.setVisible(false);
    }//GEN-LAST:event_bVolverCActionPerformed

    private void bAceptarCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bAceptarCMouseClicked
        // TODO add your handling code here:
        String nombre = this.NombreCuenta.getText();
        String contraseña = this.ContraseñaCuenta.getText();
        String email = this.EmailCuenta.getText();
        String telefono = this.TelefonoCuenta.getText();

        String contraseñaRegexp = ".{4,16}";
        String nombreRegexp = "^[a-zA-Z].*";
        String emailRegexp = "[^@]+@[^@]+\\.[a-zA-Z]{2,}";
        String telefonoRegexp = "[0-9]{9}";

        if (Pattern.matches(nombreRegexp, nombre) == false){
           JOptionPane.showMessageDialog(null, 
           "El nombre de usuario debe empezar por una letra",
           "Nombre de usuario no válido", 
           JOptionPane.INFORMATION_MESSAGE);
           this.NombreCuenta.setText("");
        }else if (Pattern.matches(contraseñaRegexp, contraseña) == false){
            JOptionPane.showMessageDialog(null, 
            "La contraseña introducida debe tener entre 4 y 16 caracteres",
            "Contraseña no válida", 
            JOptionPane.INFORMATION_MESSAGE);
            this.ContraseñaCuenta.setText("");
        }else if (Pattern.matches(emailRegexp, email) == false){
            JOptionPane.showMessageDialog(null, 
            "El email introducido es incorrecto",
            "Email no válido", 
            JOptionPane.INFORMATION_MESSAGE);
            this.EmailCuenta.setText("");
        } else if (Pattern.matches(telefonoRegexp, telefono) == false){
            JOptionPane.showMessageDialog(null, 
            "El telefono introducido es incorrecto",
            "Telefono no válido", 
            JOptionPane.INFORMATION_MESSAGE);
            this.TelefonoCuenta.setText("");
        } else if(this.granCarnaryRent.addUsuario(nombre, contraseña, email, telefono)==true){
            JOptionPane.showMessageDialog(null, 
            "Bienvenido a GranCarnaryRent",
            "Usuario creado con éxito",
            JOptionPane.INFORMATION_MESSAGE);
            
            PantallaInicio abrir = new PantallaInicio(granCarnaryRent);
            abrir.setVisible(true);

            this.setVisible(false);
        } else{
            JOptionPane.showMessageDialog(null, 
            "El nombre de usuario o el email introducido ya existe",
            "Email o nombre de usuario no válido", 
            JOptionPane.INFORMATION_MESSAGE);
        }     
    }//GEN-LAST:event_bAceptarCMouseClicked

    private void EmailCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailCuentaActionPerformed

    private void TelefonoCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelefonoCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TelefonoCuentaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaCrearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaCrearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaCrearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaCrearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaCrearCuenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ContraseñaCuenta;
    private javax.swing.JTextField EmailCuenta;
    private javax.swing.JTextField NombreCuenta;
    private javax.swing.JLabel Telefono;
    private javax.swing.JTextField TelefonoCuenta;
    private javax.swing.JButton bAceptarC;
    private javax.swing.JButton bVolverC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lContraseñaC;
    private javax.swing.JLabel lEmailC;
    private javax.swing.JLabel lNombreC;
    // End of variables declaration//GEN-END:variables
}
