/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import model.GranCarnaryRent;
import model.Reserva;
import model.Usuario;

/**
 *
 * @author diego
 */
public class ResumenReserva extends javax.swing.JFrame {

    private GranCarnaryRent granCarnaryRent;
    private Usuario user;
    private Reserva reserva;

    /**
     * Creates new form ResumenReserva
     */
    public ResumenReserva() {
        initComponents();
    }

    public ResumenReserva(GranCarnaryRent granCarnaryRent, Usuario user, Reserva reserva) {
        this.granCarnaryRent = granCarnaryRent;
        this.user = user;
        this.reserva = reserva;
        initComponents();
        this.setLocationRelativeTo(null);
        
        Date date = reserva.getFechaRecogida();  
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");  
        String strDate = dateFormat.format(date);  
        fechaRecogidaLabel.setText(strDate);
        date = reserva.getFechaEntrega();  
        dateFormat = new SimpleDateFormat("dd/MM/yyyy");  
        strDate = dateFormat.format(date);
        fechaEntregaLabel.setText(strDate);
        
        oficinaRecogidaLabel.setText(reserva.getOficinaRecogida().getDireccion());
        oficinaEntregaLabel.setText(reserva.getOficinaEntrega().getDireccion());
        vehiculoLabel.setText(reserva.getVehiculoReservado().getModelo());
        seguroLabel.setText(reserva.getSeguroSeleccionado().getNombreSeguro());
        
        if (reserva.getServiciosSeleccionados().size() == 0) {
            serviciosLabel.setText("Sin servicios extra");
        } else {
            String result = "";
            for (int i= 0; i<reserva.getServiciosSeleccionados().size(); i++){
                result += reserva.getServiciosSeleccionados().get(i).getNombreServicio();
                if (i+1>=reserva.getServiciosSeleccionados().size()){
                    break;
                }
                result += ", ";
            }
            serviciosLabel.setText(result);
        }
        
        String result = String.format("Subtotal: %.2f €", reserva.getPrecio());
        subtotalLabel.setText(result);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        pagarDespuesButton = new javax.swing.JButton();
        pagarAhoraButton = new javax.swing.JButton();
        subtotalLabel = new javax.swing.JLabel();
        fechaRecogidaLabel = new javax.swing.JLabel();
        fechaEntregaLabel = new javax.swing.JLabel();
        oficinaRecogidaLabel = new javax.swing.JLabel();
        oficinaEntregaLabel = new javax.swing.JLabel();
        vehiculoLabel = new javax.swing.JLabel();
        seguroLabel = new javax.swing.JLabel();
        serviciosLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel5.setFont(new java.awt.Font("Malgun Gothic", 1, 22)); // NOI18N
        jLabel5.setText("RESUMEN RESERVA");

        jLabel1.setText("Fecha recogida:");

        jLabel2.setText("Fecha entrega:");

        jLabel3.setText("Oficina recogida:");

        jLabel4.setText("Oficina entrega:");

        jLabel6.setText("Vehículo:");

        jLabel7.setText("Seguro:");

        jLabel8.setText("Servicios:");

        pagarDespuesButton.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        pagarDespuesButton.setText("Pagar más tarde");
        pagarDespuesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagarDespuesButtonActionPerformed(evt);
            }
        });

        pagarAhoraButton.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        pagarAhoraButton.setText("Pagar ahora");
        pagarAhoraButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagarAhoraButtonActionPerformed(evt);
            }
        });

        subtotalLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        subtotalLabel.setForeground(new java.awt.Color(255, 0, 0));
        subtotalLabel.setText("jLabel1");

        fechaRecogidaLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fechaRecogidaLabel.setText("jLabel9");

        fechaEntregaLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fechaEntregaLabel.setText("jLabel10");

        oficinaRecogidaLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        oficinaRecogidaLabel.setText("jLabel11");

        oficinaEntregaLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        oficinaEntregaLabel.setText("jLabel12");

        vehiculoLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        vehiculoLabel.setText("jLabel13");

        seguroLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        seguroLabel.setText("jLabel14");

        serviciosLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        serviciosLabel.setText("jLabel15");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pagarDespuesButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                        .addComponent(pagarAhoraButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(subtotalLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fechaRecogidaLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fechaEntregaLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(oficinaRecogidaLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(oficinaEntregaLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(vehiculoLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(seguroLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(serviciosLabel)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(fechaRecogidaLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fechaEntregaLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(oficinaRecogidaLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(oficinaEntregaLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(vehiculoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(seguroLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(serviciosLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(subtotalLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pagarDespuesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pagarAhoraButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pagarDespuesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagarDespuesButtonActionPerformed
        this.user.addReserva(reserva);
        MenuPrincipal abrir = new MenuPrincipal(this.granCarnaryRent, this.user);
        abrir.setVisible(true);

        this.setVisible(false);
    }//GEN-LAST:event_pagarDespuesButtonActionPerformed

    private void pagarAhoraButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagarAhoraButtonActionPerformed
        this.user.addReserva(reserva);
        PagarReserva abrir = new PagarReserva(this.granCarnaryRent, this.user, this.reserva);
        abrir.setVisible(true);

        this.setVisible(false);
    }//GEN-LAST:event_pagarAhoraButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResumenReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResumenReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResumenReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResumenReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResumenReserva().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fechaEntregaLabel;
    private javax.swing.JLabel fechaRecogidaLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel oficinaEntregaLabel;
    private javax.swing.JLabel oficinaRecogidaLabel;
    private javax.swing.JButton pagarAhoraButton;
    private javax.swing.JButton pagarDespuesButton;
    private javax.swing.JLabel seguroLabel;
    private javax.swing.JLabel serviciosLabel;
    private javax.swing.JLabel subtotalLabel;
    private javax.swing.JLabel vehiculoLabel;
    // End of variables declaration//GEN-END:variables
}
